"""Florida counties and starter population centers for search expansion."""

from __future__ import annotations

FLORIDA_COUNTIES = [
    "Alachua", "Baker", "Bay", "Bradford", "Brevard", "Broward", "Calhoun", "Charlotte",
    "Citrus", "Clay", "Collier", "Columbia", "DeSoto", "Dixie", "Duval", "Escambia",
    "Flagler", "Franklin", "Gadsden", "Gilchrist", "Glades", "Gulf", "Hamilton", "Hardee",
    "Hendry", "Hernando", "Highlands", "Hillsborough", "Holmes", "Indian River", "Jackson",
    "Jefferson", "Lafayette", "Lake", "Lee", "Leon", "Levy", "Liberty", "Madison", "Manatee",
    "Marion", "Martin", "Miami-Dade", "Monroe", "Nassau", "Okaloosa", "Okeechobee", "Orange",
    "Osceola", "Palm Beach", "Pasco", "Pinellas", "Polk", "Putnam", "Santa Rosa", "Sarasota",
    "Seminole", "St. Johns", "St. Lucie", "Sumter", "Suwannee", "Taylor", "Union", "Volusia",
    "Wakulla", "Walton", "Washington",
]

COUNTY_TO_CITIES = {
    "Alachua": ["Gainesville", "Alachua", "Newberry", "High Springs"],
    "Baker": ["Macclenny", "Glen St. Mary"],
    "Bay": ["Panama City", "Lynn Haven", "Callaway", "Panama City Beach"],
    "Bradford": ["Starke", "Lawtey"],
    "Brevard": ["Melbourne", "Palm Bay", "Titusville", "Cocoa"],
    "Broward": ["Fort Lauderdale", "Hollywood", "Pembroke Pines", "Coral Springs"],
    "Calhoun": ["Blountstown", "Altha"],
    "Charlotte": ["Punta Gorda", "Port Charlotte", "Englewood"],
    "Citrus": ["Inverness", "Crystal River", "Homosassa"],
    "Clay": ["Green Cove Springs", "Orange Park", "Fleming Island", "Middleburg"],
    "Collier": ["Naples", "Marco Island", "Immokalee"],
    "Columbia": ["Lake City", "Fort White"],
    "DeSoto": ["Arcadia"],
    "Dixie": ["Cross City", "Old Town"],
    "Duval": ["Jacksonville", "Atlantic Beach", "Jacksonville Beach"],
    "Escambia": ["Pensacola", "Century", "Cantonment"],
    "Flagler": ["Palm Coast", "Flagler Beach", "Bunnell"],
    "Franklin": ["Apalachicola", "Carrabelle"],
    "Gadsden": ["Quincy", "Havana", "Chattahoochee"],
    "Gilchrist": ["Trenton", "Bell"],
    "Glades": ["Moore Haven"],
    "Gulf": ["Port St. Joe", "Wewahitchka"],
    "Hamilton": ["Jasper", "Jennings"],
    "Hardee": ["Wauchula", "Bowling Green"],
    "Hendry": ["LaBelle", "Clewiston"],
    "Hernando": ["Brooksville", "Spring Hill", "Weeki Wachee"],
    "Highlands": ["Sebring", "Avon Park", "Lake Placid"],
    "Hillsborough": ["Tampa", "Brandon", "Plant City", "Riverview"],
    "Holmes": ["Bonifay", "Ponce de Leon"],
    "Indian River": ["Vero Beach", "Sebastian"],
    "Jackson": ["Marianna", "Graceville"],
    "Jefferson": ["Monticello"],
    "Lafayette": ["Mayo"],
    "Lake": ["Leesburg", "Clermont", "Eustis", "Tavares"],
    "Lee": ["Fort Myers", "Cape Coral", "Bonita Springs", "Lehigh Acres"],
    "Leon": ["Tallahassee"],
    "Levy": ["Bronson", "Chiefland", "Williston"],
    "Liberty": ["Bristol"],
    "Madison": ["Madison", "Greenville"],
    "Manatee": ["Bradenton", "Palmetto", "Lakewood Ranch"],
    "Marion": ["Ocala", "Belleview", "Dunnellon"],
    "Martin": ["Stuart", "Jensen Beach"],
    "Miami-Dade": ["Miami", "Hialeah", "Homestead", "Miami Beach"],
    "Monroe": ["Key West", "Marathon", "Key Largo"],
    "Nassau": ["Fernandina Beach", "Yulee", "Callahan"],
    "Okaloosa": ["Fort Walton Beach", "Destin", "Crestview", "Niceville"],
    "Okeechobee": ["Okeechobee"],
    "Orange": ["Orlando", "Winter Park", "Apopka", "Ocoee"],
    "Osceola": ["Kissimmee", "St. Cloud", "Celebration"],
    "Palm Beach": ["West Palm Beach", "Boca Raton", "Delray Beach", "Boynton Beach"],
    "Pasco": ["New Port Richey", "Dade City", "Wesley Chapel"],
    "Pinellas": ["St. Petersburg", "Clearwater", "Largo", "Dunedin"],
    "Polk": ["Lakeland", "Winter Haven", "Bartow", "Haines City"],
    "Putnam": ["Palatka", "Crescent City"],
    "Santa Rosa": ["Milton", "Pace", "Navarre"],
    "Sarasota": ["Sarasota", "North Port", "Venice"],
    "Seminole": ["Sanford", "Altamonte Springs", "Oviedo", "Lake Mary"],
    "St. Johns": ["St. Augustine", "Ponte Vedra Beach"],
    "St. Lucie": ["Port St. Lucie", "Fort Pierce", "St. Lucie Village"],
    "Sumter": ["Bushnell", "Wildwood", "The Villages"],
    "Suwannee": ["Live Oak"],
    "Taylor": ["Perry"],
    "Union": ["Lake Butler", "Raiford"],
    "Volusia": ["Daytona Beach", "Deltona", "DeLand", "New Smyrna Beach"],
    "Wakulla": ["Crawfordville", "Sopchoppy"],
    "Walton": ["DeFuniak Springs", "Santa Rosa Beach", "Freeport"],
    "Washington": ["Chipley", "Vernon"],
}


def get_cities_for_county(county: str) -> list[str]:
    """Return starter cities for a county (always at least the county name fallback)."""
    return COUNTY_TO_CITIES.get(county, [county])
